//
//  ClockStyleKit.swift
//  NookaTime
//
//  Created by Alex Jacobs on 5/11/15.
//  Copyright (c) 2015 Nooka. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class ClockStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var color1: UIColor = UIColor(red: 0.884, green: 0.000, blue: 0.468, alpha: 1.000)
    }

    //// Colors

    public class var color1: UIColor { return Cache.color1 }

    //// Drawing Methods

    public class func drawCanvas0() {
        //// Color Declarations
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)

        
        //// HOUR1 Drawing
        var eMPTY1Path = UIBezierPath(ovalInRect: CGRectMake(127, 49.47, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY1Path.lineWidth = 1
        eMPTY1Path.stroke()
        
        //// EMPTY12 Drawing
        var eMPTY12Path = UIBezierPath(ovalInRect: CGRectMake(96.25, 41.23, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY12Path.lineWidth = 1
        eMPTY12Path.stroke()


        //// EMPTY2 Drawing
        var eMPTY2Path = UIBezierPath(ovalInRect: CGRectMake(149.51, 71.98, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY2Path.lineWidth = 1
        eMPTY2Path.stroke()


        //// EMPTY3 Drawing
        var eMPTY3Path = UIBezierPath(ovalInRect: CGRectMake(157.75, 102.73, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY3Path.lineWidth = 1
        eMPTY3Path.stroke()


        //// EMPTY4 Drawing
        var eMPTY4Path = UIBezierPath(ovalInRect: CGRectMake(149.51, 133.48, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY4Path.lineWidth = 1
        eMPTY4Path.stroke()


        //// EMPTY5 Drawing
        var eMPTY5Path = UIBezierPath(ovalInRect: CGRectMake(127, 155.99, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY5Path.lineWidth = 1
        eMPTY5Path.stroke()


        //// EMPTY6 Drawing
        var eMPTY6Path = UIBezierPath(ovalInRect: CGRectMake(96.25, 164.23, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY6Path.lineWidth = 1
        eMPTY6Path.stroke()


        //// EMPTY7 Drawing
        var eMPTY7Path = UIBezierPath(ovalInRect: CGRectMake(65.5, 155.99, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY7Path.lineWidth = 1
        eMPTY7Path.stroke()


        //// EMPTY8 Drawing
        var eMPTY8Path = UIBezierPath(ovalInRect: CGRectMake(42.99, 133.48, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY8Path.lineWidth = 1
        eMPTY8Path.stroke()


        //// EMPTY9 Drawing
        var eMPTY9Path = UIBezierPath(ovalInRect: CGRectMake(34.75, 102.73, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY9Path.lineWidth = 1
        eMPTY9Path.stroke()


        //// EMPTY10 Drawing
        var eMPTY10Path = UIBezierPath(ovalInRect: CGRectMake(42.99, 71.98, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY10Path.lineWidth = 1
        eMPTY10Path.stroke()


        //// EMPTY11 Drawing
        var eMPTY11Path = UIBezierPath(ovalInRect: CGRectMake(65.5, 49.47, 24, 24))
        ClockStyleKit.color1.setStroke()
        eMPTY11Path.lineWidth = 1
        eMPTY11Path.stroke()
    }
    
    public class func drawCanvas12() {
            
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR12 Drawing
        var hOUR12Path = UIBezierPath(ovalInRect: CGRectMake(96.25, 41.23, 24, 24))
        color0.setFill()
        hOUR12Path.fill()
        
    }
    
    public class func drawCanvas01() {
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR1 Drawing
        var hOUR1Path = UIBezierPath(ovalInRect: CGRectMake(127, 49.47, 24, 24))
        color0.setFill()
        hOUR1Path.fill()
    }
    
    public class func drawCanvas02() {
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR2 Drawing
        var hOUR2Path = UIBezierPath(ovalInRect: CGRectMake(149.51, 71.98, 24, 24))
        color0.setFill()
        hOUR2Path.fill()
        
    }
    
    public class func drawCanvas03() {
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)    
        //// HOUR3 Drawing
        var hOUR3Path = UIBezierPath(ovalInRect: CGRectMake(157.75, 102.73, 24, 24))
        color0.setFill()
        hOUR3Path.fill()
    }
    
    
    public class func drawCanvas04() {
        
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR4 Drawing
        var hOUR4Path = UIBezierPath(ovalInRect: CGRectMake(149.51, 133.48, 24, 24))
        color0.setFill()
        hOUR4Path.fill()
    
    }

    public class func drawCanvas05() {
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR5 Drawing
        var hOUR5Path = UIBezierPath(ovalInRect: CGRectMake(127, 155.99, 24, 24))
        color0.setFill()
        hOUR5Path.fill()
        
    }

    public class func drawCanvas06() {
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR6 Drawing
        var hOUR6Path = UIBezierPath(ovalInRect: CGRectMake(96.25, 164.23, 24, 24))
        color0.setFill()
        hOUR6Path.fill()
    
        
    }

    public class func drawCanvas07() {
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR7 Drawing
        var hOUR7Path = UIBezierPath(ovalInRect: CGRectMake(65.5, 155.99, 24, 24))
        color0.setFill()
        hOUR7Path.fill()
    
    }
    public class func drawCanvas08() {
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR8 Drawing
        var hOUR8Path = UIBezierPath(ovalInRect: CGRectMake(42.99, 133.48, 24, 24))
        color0.setFill()
        hOUR8Path.fill()
    
    }

    public class func drawCanvas09() {
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR9 Drawing
        var hOUR9Path = UIBezierPath(ovalInRect: CGRectMake(34.75, 102.73, 24, 24))
        color0.setFill()
        hOUR9Path.fill()
    
    }

    public class func drawCanvas10() {
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR10 Drawing
        var hOUR10Path = UIBezierPath(ovalInRect: CGRectMake(42.99, 71.98, 24, 24))
        color0.setFill()
        hOUR10Path.fill()
    
    }

    public class func drawCanvas11() {
    
        let color0 = UIColor(red: 0.894, green: 0.000, blue: 0.476, alpha: 1.000)
        //// HOUR11 Drawing
        var hOUR11Path = UIBezierPath(ovalInRect: CGRectMake(65.5, 49.47, 24, 24))
        color0.setFill()
        hOUR11Path.fill()
    }

    
}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
